;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        easy-kill
        kill-region
        ns-copy-including-secondary
        paredit-backward-kill-word
        prelude-move-beginning-of-line
        sp-down-sexp
        ))

(setq mc/cmds-to-run-once
      '(
        undo-tree-visualize
        ))
